// AUTO-GENERATED — DO NOT EDIT THIS FILE
// Source of truth: ~/apps/_shared/smart-url.ts
// To update: edit the source, then run: bash ~/apps/_shared/setup.sh

/**
 * House of Sports - Centralized URL Resolution
 * 
 * ONE file. ALL apps. NEVER duplicate this logic.
 * 
 * This file is symlinked into every app's src/lib/ directory.
 * To update URL behavior, edit THIS file only:
 *   ~/apps/_shared/smart-url.ts
 * 
 * Changes propagate to all apps instantly (symlink).
 * 
 * Usage in any component:
 *   import { smartUrl, TAILSCALE_HOST } from '@/lib/smart-url';
 *   <a href={smartUrl(3014, "/dashboard")}>Financial</a>
 */

// ============================================================
// CONFIGURATION - Edit these if infrastructure changes
// ============================================================
export const TAILSCALE_HOST = "kevins-mac-mini.tailc5323b.ts.net";
export const NAV_PORT = 3006;

// ============================================================
// DETECTION - Are we local or remote?
// ============================================================
export function isLocalAccess(): boolean {
  if (typeof window === "undefined") return true; // SSR = assume local
  const h = window.location.hostname;
  return h === "localhost" || h === "127.0.0.1";
}

// ============================================================
// URL BUILDERS
// ============================================================

/**
 * Build a URL that resolves to localhost or Tailscale
 * based on where the user is accessing from.
 * 
 * @param port - App port number (e.g. 3014)
 * @param path - Optional path (e.g. "/dashboard/taxes")
 * @returns Full URL string
 * 
 * @example
 *   smartUrl(3014)                    // "http://localhost:3014" or "https://host.ts.net:3014"
 *   smartUrl(3014, "/dashboard")      // "http://localhost:3014/dashboard" or "https://host.ts.net:3014/dashboard"
 *   smartUrl(3002, `/invoice/${id}`)  // template literals work too
 */
export function smartUrl(port: number, path: string = ""): string {
  const local = isLocalAccess();
  const base = local
    ? `http://localhost:${port}`
    : `https://${TAILSCALE_HOST}:${port}`;
  return `${base}${path}`;
}

/**
 * Get the nav.js script URL (for dynamic loading in layout).
 */
export function navScriptUrl(): string {
  return smartUrl(NAV_PORT, "/nav.js");
}

// ============================================================
// APP DIRECTORY - All House of Sports apps and their ports
// ============================================================
export const APP_PORTS = {
  "jane-dashboard": 3000,
  "financial": 3014,
  "content": 3007,
  "marketing": 3012,
  "support": 3024,
  "parent-comm": 3028,
  "tbf": 3018,
  "ra1": 3020,
  "facility": 3016,
  "gear-store": 3032,
  "software": 3022,
  "voice-hub": 3333,
  "cfo-app": 3002,
  "ra1-dashboard": 3005,
  "gear-store-app": 3003,
  "shadow-coach": 3006,
} as const;

export type AppName = keyof typeof APP_PORTS;

/**
 * Get URL for a named app.
 * 
 * @example
 *   appUrl("financial")                    // "http://localhost:3014"
 *   appUrl("financial", "/dashboard")      // "http://localhost:3014/dashboard"
 *   appUrl("voice-hub")                    // "http://localhost:3333"
 */
export function appUrl(app: AppName, path: string = ""): string {
  return smartUrl(APP_PORTS[app], path);
}
