// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/apps/formbricks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/apps/formbricks">> = Specific
  const handler = {} as typeof import("../../src/app/apps/formbricks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/apps/listmonk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/apps/listmonk">> = Specific
  const handler = {} as typeof import("../../src/app/apps/listmonk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/apps/mautic/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/apps/mautic">> = Specific
  const handler = {} as typeof import("../../src/app/apps/mautic/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/apps/postiz/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/apps/postiz">> = Specific
  const handler = {} as typeof import("../../src/app/apps/postiz/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/apps/umami/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/apps/umami">> = Specific
  const handler = {} as typeof import("../../src/app/apps/umami/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/files/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/files">> = Specific
  const handler = {} as typeof import("../../src/app/files/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leads">> = Specific
  const handler = {} as typeof import("../../src/app/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/opencli/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/opencli">> = Specific
  const handler = {} as typeof import("../../src/app/opencli/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pipeline/assembly/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipeline/assembly">> = Specific
  const handler = {} as typeof import("../../src/app/pipeline/assembly/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pipeline/brand-pods/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipeline/brand-pods">> = Specific
  const handler = {} as typeof import("../../src/app/pipeline/brand-pods/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pipeline/campaigns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipeline/campaigns">> = Specific
  const handler = {} as typeof import("../../src/app/pipeline/campaigns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pipeline/content-assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipeline/content-assets">> = Specific
  const handler = {} as typeof import("../../src/app/pipeline/content-assets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pipeline/content-distribution/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipeline/content-distribution">> = Specific
  const handler = {} as typeof import("../../src/app/pipeline/content-distribution/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pipeline/control/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipeline/control">> = Specific
  const handler = {} as typeof import("../../src/app/pipeline/control/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pipeline/creative-briefs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipeline/creative-briefs">> = Specific
  const handler = {} as typeof import("../../src/app/pipeline/creative-briefs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pipeline/deployments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipeline/deployments">> = Specific
  const handler = {} as typeof import("../../src/app/pipeline/deployments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pipeline/email-analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipeline/email-analytics">> = Specific
  const handler = {} as typeof import("../../src/app/pipeline/email-analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pipeline/email-config/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipeline/email-config">> = Specific
  const handler = {} as typeof import("../../src/app/pipeline/email-config/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pipeline/intelligence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipeline/intelligence">> = Specific
  const handler = {} as typeof import("../../src/app/pipeline/intelligence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pipeline/learning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipeline/learning">> = Specific
  const handler = {} as typeof import("../../src/app/pipeline/learning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pipeline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipeline">> = Specific
  const handler = {} as typeof import("../../src/app/pipeline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pipeline/performance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipeline/performance">> = Specific
  const handler = {} as typeof import("../../src/app/pipeline/performance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pipeline/quality-gate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipeline/quality-gate">> = Specific
  const handler = {} as typeof import("../../src/app/pipeline/quality-gate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pipeline/seasonal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipeline/seasonal">> = Specific
  const handler = {} as typeof import("../../src/app/pipeline/seasonal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pipeline/tv-shows/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipeline/tv-shows">> = Specific
  const handler = {} as typeof import("../../src/app/pipeline/tv-shows/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools">> = Specific
  const handler = {} as typeof import("../../src/app/tools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/api/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/app-health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/app-health">> = Specific
  const handler = {} as typeof import("../../src/app/api/app-health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/apps/formbricks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/apps/formbricks">> = Specific
  const handler = {} as typeof import("../../src/app/api/apps/formbricks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/apps/mautic/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/apps/mautic">> = Specific
  const handler = {} as typeof import("../../src/app/api/apps/mautic/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/apps/postiz/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/apps/postiz">> = Specific
  const handler = {} as typeof import("../../src/app/api/apps/postiz/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/apps/umami/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/apps/umami">> = Specific
  const handler = {} as typeof import("../../src/app/api/apps/umami/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/automation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/automation">> = Specific
  const handler = {} as typeof import("../../src/app/api/automation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/automation/toggle/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/automation/toggle">> = Specific
  const handler = {} as typeof import("../../src/app/api/automation/toggle/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/brand-email-config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/brand-email-config">> = Specific
  const handler = {} as typeof import("../../src/app/api/brand-email-config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/campaign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/campaign">> = Specific
  const handler = {} as typeof import("../../src/app/api/campaign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contacts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts">> = Specific
  const handler = {} as typeof import("../../src/app/api/contacts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/content-distribution/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content-distribution/approve">> = Specific
  const handler = {} as typeof import("../../src/app/api/content-distribution/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/content-distribution/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content-distribution/config">> = Specific
  const handler = {} as typeof import("../../src/app/api/content-distribution/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/content-distribution/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content-distribution/send">> = Specific
  const handler = {} as typeof import("../../src/app/api/content-distribution/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/content-intake/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content-intake">> = Specific
  const handler = {} as typeof import("../../src/app/api/content-intake/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/marketing-pipeline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/marketing-pipeline">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/marketing-pipeline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/pipeline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/pipeline">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/pipeline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/email-analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email-analytics">> = Specific
  const handler = {} as typeof import("../../src/app/api/email-analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/email-collector/gmail-scan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email-collector/gmail-scan">> = Specific
  const handler = {} as typeof import("../../src/app/api/email-collector/gmail-scan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/email-collector/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email-collector/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/email-collector/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/email-filter/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email-filter">> = Specific
  const handler = {} as typeof import("../../src/app/api/email-filter/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/email/lists/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email/lists">> = Specific
  const handler = {} as typeof import("../../src/app/api/email/lists/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/email/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/email/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/files/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/files">> = Specific
  const handler = {} as typeof import("../../src/app/api/files/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/funnel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/funnel">> = Specific
  const handler = {} as typeof import("../../src/app/api/funnel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/gmail/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gmail">> = Specific
  const handler = {} as typeof import("../../src/app/api/gmail/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inboxes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inboxes">> = Specific
  const handler = {} as typeof import("../../src/app/api/inboxes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leads/ingest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/ingest">> = Specific
  const handler = {} as typeof import("../../src/app/api/leads/ingest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/marketing-pipeline/auto-advance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketing-pipeline/auto-advance">> = Specific
  const handler = {} as typeof import("../../src/app/api/marketing-pipeline/auto-advance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/marketing-pipeline/intake/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketing-pipeline/intake">> = Specific
  const handler = {} as typeof import("../../src/app/api/marketing-pipeline/intake/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/marketing-pipeline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketing-pipeline">> = Specific
  const handler = {} as typeof import("../../src/app/api/marketing-pipeline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/opencli/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/opencli/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/api/opencli/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/opencli/audit-log/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/opencli/audit-log">> = Specific
  const handler = {} as typeof import("../../src/app/api/opencli/audit-log/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/opencli/email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/opencli/email">> = Specific
  const handler = {} as typeof import("../../src/app/api/opencli/email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/opencli/exec/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/opencli/exec">> = Specific
  const handler = {} as typeof import("../../src/app/api/opencli/exec/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/opencli/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/opencli/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/opencli/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/opencli/integrations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/opencli/integrations">> = Specific
  const handler = {} as typeof import("../../src/app/api/opencli/integrations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/opencli/marketing-ops/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/opencli/marketing-ops">> = Specific
  const handler = {} as typeof import("../../src/app/api/opencli/marketing-ops/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/opencli/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/opencli/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/opencli/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/opencli/retry-queue/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/opencli/retry-queue">> = Specific
  const handler = {} as typeof import("../../src/app/api/opencli/retry-queue/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/opencli/unified-post/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/opencli/unified-post">> = Specific
  const handler = {} as typeof import("../../src/app/api/opencli/unified-post/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/assembly/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/assembly">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/assembly/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/auto-assembly/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/auto-assembly">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/auto-assembly/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/auto-brief-advance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/auto-brief-advance">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/auto-brief-advance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/auto-campaigns/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/auto-campaigns">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/auto-campaigns/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/auto-content-assets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/auto-content-assets">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/auto-content-assets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/auto-deploy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/auto-deploy">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/auto-deploy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/auto-full-cycle/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/auto-full-cycle">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/auto-full-cycle/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/auto-intelligence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/auto-intelligence">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/auto-intelligence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/auto-learning/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/auto-learning">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/auto-learning/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/auto-lifecycle/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/auto-lifecycle">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/auto-lifecycle/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/auto-optimize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/auto-optimize">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/auto-optimize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/auto-posthog-analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/auto-posthog-analytics">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/auto-posthog-analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/auto-prune-intel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/auto-prune-intel">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/auto-prune-intel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/auto-prune-learning/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/auto-prune-learning">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/auto-prune-learning/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/auto-quality-gate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/auto-quality-gate">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/auto-quality-gate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/auto-report-committee/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/auto-report-committee">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/auto-report-committee/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/auto-rss-intel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/auto-rss-intel">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/auto-rss-intel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/auto-seasonal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/auto-seasonal">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/auto-seasonal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/autonomy-score/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/autonomy-score">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/autonomy-score/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/brand-pods/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/brand-pods">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/brand-pods/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/campaigns/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/campaigns">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/campaigns/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/content-assets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/content-assets">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/content-assets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/creative-briefs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/creative-briefs">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/creative-briefs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/deployments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/deployments">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/deployments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/intelligence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/intelligence">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/intelligence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/learning/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/learning">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/learning/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/performance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/performance">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/performance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/quality-gate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/quality-gate">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/quality-gate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/seasonal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/seasonal">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/seasonal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pipeline/tv-shows/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/tv-shows">> = Specific
  const handler = {} as typeof import("../../src/app/api/pipeline/tv-shows/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sendmails/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sendmails">> = Specific
  const handler = {} as typeof import("../../src/app/api/sendmails/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/social-post/content-teaser/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social-post/content-teaser">> = Specific
  const handler = {} as typeof import("../../src/app/api/social-post/content-teaser/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/social-post/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social-post">> = Specific
  const handler = {} as typeof import("../../src/app/api/social-post/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscribers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscribers">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscribers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscribers/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscribers/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscribers/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/wizard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wizard">> = Specific
  const handler = {} as typeof import("../../src/app/api/wizard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
